server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/automotriz
    username: postgres
    password: James0621.
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true